FROM node:16-alpine

WORKDIR /usr/src/app

COPY ./package*.json ./
COPY ./frontend/package*.json ./frontend/

RUN npm run buildCiFrontend

COPY ./frontend/ ./frontend/

ARG APP_WEBCHAT_API
ENV REACT_APP_WEBCHAT_API ${APP_WEBCHAT_API}
RUN npm run buildFrontend

EXPOSE 3000

CMD ["npx", "serve", "frontend/build"]