FROM node:16-alpine

WORKDIR /usr/src/app

COPY ./package*.json ./
COPY ./backend/package*.json ./backend/

RUN npm run buildCiBackend

COPY ./backend/ ./backend/
RUN npm run buildBackend

ENV BACKEND_PORT=4000
ENV MONGODB_URL=mongodb://db:27017/webchat

EXPOSE 4000
CMD ["node", "backend/dist/main.js"]