FROM node:16-alpine

WORKDIR /usr/src/app

COPY ./package*.json ./
COPY ./frontend/package*.json ./frontend/

RUN npm ci frontend

COPY ./frontend/ ./frontend/

ARG APP_TODO_API
ENV REACT_APP_TODO_API ${APP_TODO_API}
RUN npm run buildFrontend

EXPOSE 3000

CMD ["npx", "serve", "packages/frontend/build"]